"""The generated ``langgraph.json`` that serves a user's async agents.

The shipped async graphs are listed in ``langgraph.json`` beside them, inside the
installed package. A user's async agents cannot go there: that directory belongs
to the package (read-only once installed) and would be rewritten on upgrade.
So the launcher generates a config of its own, in a temp directory, that lists
both sets of graphs.

Two details make it work, and both are easy to get wrong:

**Paths must use forward slashes.** ``langgraph_api`` decides file-versus-module
with ``if "/" in path_or_module`` (``langgraph_api/graph.py``), so a Windows path
written with backslashes has no ``/`` in it and is handed to
``importlib.import_module`` — which fails on a path that plainly exists. Every
path here goes through ``Path.as_posix()``.

**The shipped graphs get absolute paths too.** They live in the package, not in
the generated directory, so a relative ``./code_review.py:graph`` would resolve
against the temp directory and find nothing.

One module per user agent, each a two-line import, keeps the user's prompt out
of generated source: ``build_user_graph`` reads the ``agent.md`` at import time,
inside the server, from the file the user actually edits.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import TYPE_CHECKING

from novacode_cli.agents.user_async_agents import graph_id_for, module_name_for

if TYPE_CHECKING:
    from collections.abc import Sequence

logger = logging.getLogger(__name__)

#: The name of the generated config, and the cwd the server is launched from.
CONFIG_NAME = "langgraph.json"

#: Header of every generated module. It never raises: a user agent whose
#: ``agent.md`` is broken sets ``graph = None``, which the server loads without
#: complaint. One bad file must not take the other agents down with it, and the
#: reason stays in the server log rather than on the dispatch that failed.
_MODULE_TEMPLATE = '''"""Generated by Nova for the user async agent {name!r}. Not a source file.

Do not edit: this whole directory is rewritten whenever the set of async agents
changes. The prompt is read from {agent_md!r} at import time, so editing the
agent's own file is enough to change what this agent does.
"""

from novacode_cli.agents.user_async_agents import build_user_graph

try:
    graph = build_user_graph({name!r}, {agent_md!r})
except Exception as exc:  # noqa: BLE001 — one bad agent must not stop the server
    import logging

    logging.getLogger(__name__).error(
        "async agent %r could not be built, so it will not run: %s", {name!r}, exc
    )
    graph = None
'''


def package_config_path() -> Path:
    """The shipped ``langgraph.json``, beside the graphs it registers."""
    return Path(__file__).resolve().parent / "langgraph.json"


def shipped_graphs() -> dict[str, Path]:
    """``{graph_id: module_path}`` for the graphs the package ships.

    The shipped config uses relative paths (``./code_review.py:graph``); these
    are resolved against the config's own directory, because the generated
    config lives elsewhere and cannot use them as written.
    """
    config_path = package_config_path()
    try:
        data = json.loads(config_path.read_text(encoding="utf-8"))
    except Exception:  # noqa: BLE001 — an unreadable config means no shipped graphs
        logger.warning("could not read the shipped async agent config at %s", config_path)
        return {}
    graphs = data.get("graphs") if isinstance(data, dict) else None
    if not isinstance(graphs, dict):
        return {}
    out: dict[str, Path] = {}
    for graph_id, spec in graphs.items():
        module = spec.get("path") if isinstance(spec, dict) else spec
        if not isinstance(module, str):
            continue
        module_path = (config_path.parent / module.partition(":")[0]).resolve()
        if module_path.is_file():
            out[graph_id] = module_path
    return out


def write_user_graph_modules(
    user_agents: Sequence[tuple[str, Path]], target_dir: Path
) -> dict[str, Path]:
    """Write one import-only module per user agent into *target_dir*.

    Args:
        user_agents: ``(name, agent_md_path)`` pairs, as collected by
            ``user_async_agents.collect_user_async_agents``.
        target_dir: The generated directory, already created.

    Returns:
        ``{graph_id: written_module_path}``. An agent that cannot be turned into
        a graph id is skipped, having already been reported by the collector.
    """
    written: dict[str, Path] = {}
    for name, agent_md in user_agents:
        try:
            graph_id = graph_id_for(name)
        except ValueError as exc:
            logger.warning("not generating a graph for %s: %s", name, exc)
            continue
        module_path = target_dir / f"{module_name_for(graph_id)}.py"
        module_path.write_text(
            _MODULE_TEMPLATE.format(name=graph_id, agent_md=str(agent_md)),
            encoding="utf-8",
        )
        written[graph_id] = module_path
    return written


def build_config(
    user_graph_modules: dict[str, Path], *, extra_graphs: dict[str, Path] | None = None
) -> dict[str, object]:
    """The config mapping every graph id to ``"<abs posix path>.py:graph"``.

    Args:
        user_graph_modules: ``{graph_id: generated_module_path}``.
        extra_graphs: Other graphs to register, e.g. the shipped ones. Values are
            module paths; the ``:graph`` attribute is appended here.

    Returns:
        A config dict ready to be written as JSON. Sorted by graph id so two
        runs over the same agents produce byte-identical files.
    """
    modules: dict[str, Path] = {}
    for graph_id, module_path in (extra_graphs or {}).items():
        modules[graph_id] = Path(module_path)
    modules.update({gid: Path(p) for gid, p in user_graph_modules.items()})

    graphs = {
        graph_id: f"{module_path.as_posix()}:graph" for graph_id, module_path in modules.items()
    }
    return {"graphs": dict(sorted(graphs.items())), "dependencies": ["."]}


def generate(user_agents: Sequence[tuple[str, Path]], target_dir: Path) -> tuple[Path, list[str]]:
    """Write the modules and the config for *user_agents* into *target_dir*.

    Args:
        user_agents: ``(name, agent_md_path)`` pairs.
        target_dir: The generated directory, created if absent.

    Returns:
        ``(config_path, graph_names)``, where ``graph_names`` is everything the
        server will serve, shipped agents included.
    """
    target_dir.mkdir(parents=True, exist_ok=True)
    user_graph_modules = write_user_graph_modules(user_agents, target_dir)
    config = build_config(user_graph_modules, extra_graphs=shipped_graphs())
    config_path = target_dir / CONFIG_NAME
    config_path.write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")

    graphs: dict[str, str] = config["graphs"]  # type: ignore[assignment]
    return config_path, list(graphs)
