"""WikiManager — filesystem operations for the project wiki.

The project wiki lives at ``<project_root>/.nova/wiki/`` and provides
persistent, synthesized knowledge that the agent builds up over time.
"""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path
from typing import Any

# Seed for the wiki's AGENTS.md — documents that the synthesized `wiki/` tree is
# an Obsidian vault and how the agent should write into it.
_AGENTS_MD_SEED = """# Agent Wiki Configuration

This wiki is the agent's persistent knowledge base. The `wiki/` tree is an
**Obsidian vault** — open `.nova/wiki/wiki/` in Obsidian to browse the graph.

## Flow

    Web  →  Web Clipper → Clippings/  →  Agent (/ingest)  →  Obsidian wiki (wiki/)

- `Clippings/` — **Obsidian Web Clipper inbox** (the clipper's default folder).
  Point the clipper here; whatever you save lands in this folder and `/ingest`
  picks it up.
- `raw/` — legacy / categorized sources (`articles/`, `docs/`, …); also scanned.
- `wiki/` — synthesized, interlinked Obsidian pages
  - `technologies/`, `frameworks/`, `patterns/`, `projects/`, `comparisons/`
- `index.md` — machine-parsed topic index (markdown links)
- `log.md` — ingestion log
- `README.md` — this file

## Page conventions (Obsidian-native)

Every synthesized page has:
- **YAML frontmatter**: `title`, `aliases`, `tags`, `source`, `created`
- **`[[wikilinks]]`** to related pages (by filename-without-extension) — these
  build the Obsidian graph and backlinks
- Headings, a short summary, and scannable bullets

## Commands

- `/ingest [<path>]` — ingest a raw source into synthesized pages (no arg lists
  available raw sources; a bare filename is found anywhere under `raw/`)
- `/ask <question>` — answer with relevant wiki pages prepended as context
- `/file <topic>` — file recent conversation knowledge as a wiki page
"""


class WikiManager:
    """Handles all wiki filesystem operations.

    Usage::

        mgr = WikiManager()
        mgr.ensure_structure()
        mgr.write_page("technologies", "LangGraph", content="...")
    """

    def __init__(self, wiki_root: str | Path | None = None) -> None:
        """If *wiki_root* is omitted, resolve from the project settings."""
        if wiki_root is not None:
            self._root = Path(wiki_root)
        else:
            from novacode_cli.config.config import settings

            root = settings.ensure_project_deepagents_dir()
            if root is None:
                msg = "Not in a git repository — wiki requires a project root."
                raise RuntimeError(msg)
            self._root = root / "wiki"

    # -- paths ---------------------------------------------------------------

    @property
    def root(self) -> Path:
        return self._root

    # -- structure -----------------------------------------------------------

    def ensure_structure(self) -> None:
        """Create all wiki directories and seed files if they don't exist."""
        dirs = [
            # The Obsidian Web Clipper inbox (primary drop zone for clipped web
            # content) — matches the clipper's default "Clippings" folder name.
            # /ingest scans this first.
            self._root / "Clippings",
            # Legacy / categorized raw inputs (still scanned by /ingest).
            self._root / "raw" / "articles",
            self._root / "raw" / "docs",
            self._root / "raw" / "github",
            self._root / "raw" / "papers",
            self._root / "wiki" / "technologies",
            self._root / "wiki" / "frameworks",
            self._root / "wiki" / "patterns",
            self._root / "wiki" / "projects",
            self._root / "wiki" / "comparisons",
        ]
        for d in dirs:
            d.mkdir(parents=True, exist_ok=True)

        # Seed files
        index_path = self._root / "index.md"
        if not index_path.exists():
            index_path.write_text(
                "# Wiki Index\n\nAuto-generated by the /ingest, /ask, and /file commands.\n\n",
                encoding="utf-8",
            )

        log_path = self._root / "log.md"
        if not log_path.exists():
            log_path.write_text(
                "# Ingestion Log\n\n"
                "| Date | Action | Source | Target |\n"
                "|------|--------|--------|--------|\n",
                encoding="utf-8",
            )

        agents_path = self._root / "README.md"
        if not agents_path.exists():
            agents_path.write_text(_AGENTS_MD_SEED, encoding="utf-8")

    # -- read/write pages ----------------------------------------------------

    def write_page(
        self,
        topic: str,
        title: str,
        content: str,
        subtopic: str | None = None,
    ) -> Path:
        """Write a wiki page under ``wiki/<topic>/<title>.md``.

        *topic* should be one of ``technologies``, ``frameworks``, ``patterns``,
        ``projects``, or ``comparisons``.  *title* is kebab-case (e.g.
        ``langgraph-supervisor.md``).  Returns the written path.
        """
        if subtopic:
            topic_dir = self._root / "wiki" / topic / subtopic
        else:
            topic_dir = self._root / "wiki" / topic
        page = topic_dir / f"{title}"
        page = self._contained_page(page)
        page.parent.mkdir(parents=True, exist_ok=True)
        page.write_text(content.strip() + "\n", encoding="utf-8")
        return page

    def read_page(self, virtual_path: str | Path) -> str | None:
        """Read a wiki page given a path like ``technologies/LangGraph.md``."""
        full = self._contained_page(self._root / "wiki" / virtual_path)
        if not full.exists():
            return None
        return full.read_text(encoding="utf-8")

    def _contained_page(self, path: Path) -> Path:
        root = (self._root / "wiki").resolve()
        resolved = path.resolve()
        if resolved == root or not resolved.is_relative_to(root):
            raise ValueError("Wiki page path escapes wiki directory")
        return resolved

    # -- index operations ----------------------------------------------------

    def read_index(self) -> dict[str, dict[str, Any]]:
        """Parse index.md into ``{topic: {path, summary}}``."""
        index_path = self._root / "index.md"
        if not index_path.exists():
            return {}

        entries: dict[str, dict[str, Any]] = {}
        text = index_path.read_text(encoding="utf-8")
        for line in text.splitlines():
            line = line.strip()
            # Lines like: - **[topic](path)** — summary
            if line.startswith("- **["):
                try:
                    # Extract topic between **[ and ](
                    topic = line.split("**[")[1].split("](")[0]
                    # Extract path between ( and )  — take the last ) before —
                    after_bracket = line.split("](")[1]
                    path = after_bracket.split(")")[0]
                    # Extract summary after the —
                    summary = ""
                    if "—" in after_bracket:
                        summary = after_bracket.split("—", 1)[1].strip()
                    entries[topic] = {"path": path, "summary": summary}
                except (IndexError, ValueError):
                    continue
        return entries

    def update_index(
        self,
        topic: str,
        path: str,
        summary: str = "",
    ) -> None:
        """Add or update a single entry in index.md."""
        index_path = self._root / "index.md"
        entries = self.read_index()

        entries[topic] = {"path": path, "summary": summary}

        lines = [
            "# Wiki Index\n\n",
            "Auto-generated by the /ingest, /ask, and /file commands.\n\n",
        ]
        for name in sorted(entries, key=str.lower):
            e = entries[name]
            lines.append(f"- **[{name}]({e['path']})**")
            if e.get("summary"):
                lines.append(f" — {e['summary']}")
            lines.append("\n")

        index_path.write_text("".join(lines), encoding="utf-8")

    def search(self, query: str) -> list[tuple[str, str, str]]:
        """Search the wiki index for pages matching *query*.

        Returns ``[(topic, path, summary), ...]`` sorted by relevance.
        """
        q = query.lower()
        entries = self.read_index()
        results: list[tuple[str, str, str, int]] = []

        for topic, info in entries.items():
            score = 0
            if q in topic.lower():
                score += 2
            if q in info.get("summary", "").lower():
                score += 1
            if score > 0:
                results.append((topic, info["path"], info.get("summary", ""), score))

        results.sort(key=lambda x: -x[3])
        return [(t, p, s) for t, p, s, _ in results]

    # -- log operations ------------------------------------------------------

    def update_log(
        self,
        action: str,
        source: str,
        target: str,
    ) -> None:
        """Append a timestamped row to log.md."""
        log_path = self._root / "log.md"
        now = datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S UTC")
        line = f"| {now} | {action} | {source} | {target} |\n"

        # Ensure the header exists
        if not log_path.exists():
            log_path.write_text(
                "# Ingestion Log\n\n"
                "| Date | Action | Source | Target |\n"
                "|------|--------|--------|--------|\n",
                encoding="utf-8",
            )

        with log_path.open("a", encoding="utf-8") as f:
            f.write(line)
